project:
  type: book

execute:
  freeze: auto
book:
  title: "Scientific Computing"
  author: "Lance Nelson"
  date: "7/16/2022"
  sidebar:
    style: floating
  chapters:
    - part: "Python - The Basics"
      chapters:
      - index.qmd
      - chapters/basicPythonI.qmd
      - chapters/basicPythonII.qmd
      - chapters/basicPythonIII.qmd
      - chapters/listsAndTuples.qmd
      - chapters/loops.qmd
      - chapters/functions.qmd
bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo  # simplex cosmo
      dark: darkly
    max-width: 1600px
    margin: 10px 20px 30px 20px
  pdf:
    documentclass: scrreprt



