---
format: html
execute: 
  freeze: auto
  cache: true
toc: true
---

# Variables and Numbers 

[Jupyter Notebook](https://lancejnelson.github.io/PH135/jupyter/variables.ipynb)

## Variables

When performing mathematical operations, it is often desirable to store the values in *variables* for later use instead of manually typing them back in each time you need to use them.  This will reduce effort because small changes to variables can automatically propagate through your calculations.  

Attaching a value to a variable is called *assignment* and is performed using the equal sign (=), as demonstrated in the cell below:

```{python}
#| eval: true
#| echo: true

a = 5.0
b = 3
c = a + b
```

### Variable naming convention

There are some rules for allowed variable names in Python.  They are as follows:

1. Variable names must begin with a letter or an underscore (`_`)
2. Variables names must only contain letters, numbers, and underscores.
3. Variable names cannot contain spaces.
4. Variables names cannot be a word reserved by Python for something else.  These words are:

|  | Python  | reserved |words | | 
|-----|-----|-----|------|--------|
|and | as |assert | break | class |
|continue | def |del | elif | else |
|except | False |finally | for | from |
|global | if |import | in | is |
|lambda | None |nonlocal | not | or |
|pass | raise |return | True | try |
|why | with |yield |  |  |


The cell below contains some allowed variable names and some that are not allowed.


>**_To Do:_**
>
>1. Determine which variable names are allowed and which are not in the cell below.
>2. What does Python do if you try to define a variable using a name that is not allowed?

```{python}
#| echo: true
#| eval: false
my1variable = 3
1stvariables = 2
a big constant = 3
a_big_constant = 1e8
```

It is also a good practice to make variable names meaningful. For example, in the cell below we calculate $E = mc^2$ using two choices for variable assignments. In one case, it is easy to determine what the calculation is and in the other it isn't.

```{python}

# Good Variable Names
mass_kg = 1.6
light_speed = 3.0e8
energy = mass_kg * light_speed**2


# Poor Variable Names
a = 1.6
b = 3.0e8
c = a * b**2


```

## Numbers: Integers and Floats

There are two types of numbers in Python - floats and integers. *Floats*, short for "floating point numbers," are values with decimals in them.  They may be either whole or non-whole numbers such as 3.0 or 1.2, but there is always a decimal point. *Integers* are whole numbers with no decimal point such as 2 or 53.

Mathematical operations that only use integers *and* evaluate to a whole number will generate an integers (except for division).  All other situations will generate a float.  See the example cell below.


```{python}

a = 24
b = 6
d = 0.3
e = a + b # Produces an integer.
f = a + d # Produces a float
g = a * b # Produces a ???
h = a / b # Produces a ???
```


>**_To Do:_**
>
>1. For each of the mathematical operations above guess what type of number the result will be.
>2. Use `print` statements to verify your guesses and formulate a general rule that you can rely on.  (Tip, the `type()` function will tell you what kind of number a variable is.)

```{python}
# Python Code Here!
```


Integers and floats can be inter-converted to each other using the `int()` and `float()` functions.

```{python}
int(3.0)
float(4)
```

The distinction between floats and ints is often a minor detail. Occasionally, a function will require that an argument be a float or an int but usually you won't have to worry about which one you use.

Below you will find some other common mathematical operations that can be performed on numerical variables. 


```{python}
#| echo: true
#| eval: false

a = 20
b = 10
c = a + b 
d = a/b  
r = a//b
r = a % b
e = a * b
f = c**4
```


>**To Do:**
>
>1. Use print statements to investigate what each operation does.  
>2. Guess what type of number you expect the result to produce (int or float) and then check yourself?
>3. Add comments next to each line (Use `#` to start a comment) explaining that operation. 

```{python}
# Python Code Here!
```



### Augmented Assignment

Augmented assignment is a shortened way to make a simple modification to a variable. For example, if we want to increase the value of a variable by 10, one way to do it would be like this.

```{python}
a = 5
a = a + 10
```

This is certainly not difficult, but it does involve typing the variable twice which becomes cumbersome as your variable name gets longer.  Alternatively, we can accomplish the same thing with the `+=` operator.

```{python}
a = 5
a += 10
```

Augmented assignment can be used with addition, subtraction, multiplication, and division as shown in the code cell below.



```{python}
a = 7
a += 3
a -= 1
a *= 4
a /= 3
```


>**_To Do:_**
>
>1. Predict what the final result of `a` will be in the code cell above.
>2. Add an appropriately-place `print` statement to see if you were correct.
>3. If you were wrong, pow-wow with your neighbor until you understand.

```{python}
# Python Code Here!
```

### Compound Assignment

At the beginning of a program or calculation, it is often necessary to define a set of variables. Each variable may get it's own line of code, but if there are a lot of variables, this can begin to clutter your code a little.  An alternative is to assign multiple variables on a single line.  In the code below, we assign the atomic mass of the first three elements.

```{python}
H, He, Li = 1.01, 4.00, 5.39
```



>**_To Do:_**
>
>1. Use print statements to verify that each variable was assigned it's own value.
>2. Add assignments for the atomic masses of the next three elements on the periodic table.

```{python}
# Python Code Here!
```

### Large numbers

Sometimes you find yourself working with large numbers in your calculation. Maybe your calculation involves the use of ten billion, which has 10 zeros in it.  It can be difficult to look at all of those zeros with no commas to help break it up.  In those cases, you can use an underscore (`_`) in place of the comma, as shown below.  

```{python}
myLargeNumber = 10000000000 # This is tough to look at.
myLargeNumber = 10_000_000_000  # This is easy to read

myLargeFloat = 5000000.6 # This is tough to read
myLargeFloat = 5_000_000.6 # This is easy to read
```

### Very Large Numbers
If your number is very large or very small ( $20-30$ zeros), you would probably rather not have to type all of the zeros at all, even if you can break it up with the underscores.  For example, the Boltzmann constant, which comes up in thermodynamics, has a value equal to  

$$ 1.38 \times 10^{-23}$$ 

We can avoid typing all those zeros by using scientific notation when defining the variable. (see example below)  This is super handy for very large and very small numbers.  (Numbers of both variety show up frequently in physics!)

```{python}
kB = 1.38e-23
```

### Python functions

In addition to basic mathematical functions, python contains several mathematical *functions*.  As in mathematics, a function has a name (e.g. *f*) and the arguments are places inside of the parenthesis after the name.  The *argument* is any value or piece of information fed into the function.  In the case below, *f* requires a single argument *x*.
$$f(x)$$

In the cell below, you will find several useful Python functions.

```{python}
abs(-5.5)
float(2)
int(5.6)
print(1.26e-6)
round(-5.51)
str(3.2)
```

In addition to Python's native collection of mathematical functions, there is also a `math` module with more mathematical functions.  Think of a module as an add-on or tool pack for Python just like a library.  The `math` module comes with every installation of python and can be *imported* (i.e. activated) using the `import math` command. After the module has been imported, any function in the module is called using `math.function()` where `function` is the name of the function.  Below is a list of commonly-used functions inside the `math module`.  Carefully look at each of them and guess what they mean.

```{python}
import math
math.sqrt(4)
math.ceil(4.3)
math.cos(1.5)
math.sin(1.5)
math.tan(3.14)
math.asin(1)
math.acos(1/2)
math.atan(2)
math.degrees(6.28)
math.e
math.exp(5)
math.factorial(4)
math.log(200)
math.log10(1000)
math.radians(360)
math.pi
math.pow(2,8)
```



>**_To Do:_**
>
>1. Use print statements to figure out what each function in the code cell above does.   Pay special attention to trigonometric function.  Do these functions expect the argument to be in radians or degrees? 
>2. Add comments to remind yourself for later.

```{python}
# Python Code Here!
```


There are other ways to import functions from modules. If you only want to use a single function inside the module, you can selectively import it using `from`, as shown below.

```{python}
from math import radians
radians(4)
```


## Errors In Python 
When you are learning to write code, you will inevitably run into errors. Seeing a block of red text can be intimidating at first, but it's important to remember that errors are not failures; they are helpful signs. The error message is simply Python's way of telling you that it couldn't understand your instructions and often gives you a very specific clue about what went wrong.

Learning to read these messages is a fundamental skill that will turn you into a more effective programmer. Let's look at some of the most common errors you will encounter on your journey.




### Syntax Error

A `SyntaxError` is the most common type of error for beginners. It means you have broken a grammar rule of the Python language. Just like a sentence in English needs correct punctuation to make sense, a line of Python code needs correct syntax.

\textbf{Common Cause}: Missing punctuation, like a colon :, a parenthesis ), or a quotation mark ".

In the example below, we forget to close the parentheses for the print function.

```{python}
#| error: true

# We are trying to print a message, but we forgot the closing parenthesis.
print("This line has a syntax error"
```

### Indentation Error
Python is unique because it uses whitespace (specifically, the spaces at the beginning of a line) to group code together. An `IndentationError` means that the spacing in your code is not correct or consistent.

\textbf{Common Cause}: Forgetting to indent code that belongs inside a loop, function, or if statement.



```{python}
#| error: true

# The line below should be indented, because it belongs inside the for loop.
for i in range(5):
print(i)
```

You can also get an `IndentationError` if there are multiple lines indented but their indentation levels are not consistent, as shown below.


```{python}
#| error: true

# Indentation error because the lines in the loop are not all indented
# to the same position
for i in range(10):
    print(i)
     print(i**2)

```

### NameError
A `NameError` occurs when you try to use a variable or function that Python doesn't recognize.

\textbf{Common Cause}: A typo in a variable name or trying to use a variable before you have assigned it a value.

```{python}
#| error: true

# We create a variable called 'initial_velocity'.
initial_velocity = 20

# But then we make a typo when trying to print it. Python doesn't know what 'initial_velocite' is.
print(initial_velocite)
```

Since Python executes code sequentially: the first line gets executed first, then the second line, etc., you can get a `NameError` if you try to use a variable before it is defined, as shown below.
```{python}
#| error: true
dx = 5.22

v = dx/dt  # A NameError occurs at this line because dt is not yet defined.

dt = 0.4


```


### TypeError
A `TypeError` means you are trying to do an operation with a data type that doesn't support it. It's like trying to add a word to a number—it just doesn't make sense.

\textbf{Common Cause}: Trying to combine incompatible types, like adding a string and an integer.


```{python}
#| error: true

# You can't directly add a number (an integer) to a word (a string).
# Python doesn't know if you mean to do math or combine text.
message = "The answer is: " + 5

```

### IndexError
An `IndexError` happens when you try to access an item in a list using an index that is out of bounds.

\textbf{Common Cause}: Forgetting that list indices start at 0. For a list of 3 items, the only valid indices are 0, 1, and 2.

```{python}
#| error: true

# This list has three items.
planets = ["Mercury", "Venus", "Earth"]

# The valid indices are 0, 1, and 2.
# By asking for index 3, we are asking for a fourth item that doesn't exist.
print(planets[3])

```


### FileNotFoundError
This is a very common error when you start working with data. It simply means that you are trying to open a file that Python cannot find at the location you specified.

\textbf{Common Cause}: A typo in the filename or the file not being in the same folder as your script.

```{python}
#| error: true

# Python will look in the current folder for a file with this name.
# If it can't find it, it will raise this error.
with open("data_that_does_not_exist.csv") as f:
    print(f.read())
```

## Exercises

1. Most (or all) of you have use Pythagorean's theorem to calculate the hypotenuse of a right triangle. The theorem states that the lengths of a right triangle are related like this $a^2 + b^2 = c^2$, where $a$ and $b$ are the lengths of the sides forming the right angle and $c$ is the length of the hypotenuse.  There is a Python function called `hypot` (found in a library called `math`) that will perform this calculation for your.  Calculate the distance from the point $(-48,56)$ to the point $(23,81)$ using 
    1. Pythogorean's theorem
    2. The Python function `hypot`. To learn how to use the hypot function, visit the following [documentation page](https://docs.python.org/3/library/math.html) and search for the explanation for the `hypot` function.  Learning to read and understand online documentation is a skill that you you should develop.
    
Print out the result and check your answer with your neighbor's answer.

```{python}
# Python Code Here!
```


2. Equations involing quadratic polynomials,like the one shown below, appear in science frequently.  

$$ 5x^2 + 2x - 1 = 0$$

You may remember that the solution to this equation is given by the quadratic formula
$$ x = {- b \pm \sqrt{b^2 - 4 a c} \over 2a}$$
Solve the quadratic equation given above and print off the results. (There are two answers.)  Then check with a classmate to verify that your answers match.

```{python}
# Python Code Here!
```


3. (Solar Mass)  The mass of the sun can be calculated using the following formula:$$ M_\text{sun} = {4 \pi^2 (1 \text{ AU})^3\over G (1 \text{ yr})^2}$$  
The unit AU is called an astronomical unit of length and is defined to be the average distance between the sun and earth. $$ 1 \text{ AU} = 1.58\times 10^{-5} \text{ light years}$$
where $1 \text{ lightyear} = 9.5 \times 10^{15}$ m.  The constant $G$ is called the gravitational constant and has the value: $$ G = 6.674 \times 10^{-11} \text{ m}^3 \text{ kg}^{-1}\text{ s}^{-1}$$  Calculate the mass of the sun (in kg) and display your result using a print statement.  You should find a value of $M_\text{Sun} = 2.01 \times 10^{30}$ kg.  

```{python}
# Python Code Here!
```

4. (Projectile Motion)  The range of a projectile is given by the equation:$$ d = {2 v^2 \cos \theta \sin \theta \over g}$$
or the equivalent expression:$$ d = {v^2  \sin 2 \theta \over g}$$
where $g = 9.8$ m/s$^2$, $\theta$ is the launch angle, and $v$ is the launch speed.

    1. Using a launch angle of 60$^\circ$ and a launch speed of $40$ m/s, verify that both expressions above give the same result for the range.
    2. Now pick one of the equations above and use trial and error to determine the angle that gives maximum range.


```{python}
v = 40
g = 9.8


```


5. (Rydberg's constant) Rydberg's constant ($R_\infty$) is a physical constant in Rydberg's formula which was used to predict the spectrum of light emitted by a heavy atom. Rydberg's constant is given by: $$R_\infty = {m_e e^4 \over 8 \epsilon_0^2 h^3 c}$$  
where  
   - $m_e = 9.109 \times 10^{-31}$ kg is the mass of an electron.
   - $e = 1.602 \times 10^{-19}$ C is the charge of an electron/proton.
   - $\epsilon_0 = 8.854 \times 10^{-12}$ C V$^{-1}$ m$^{-1}$ is the electrical constant.
   - $h = 6.626 \times 10^{-34}$ J Hz is the Planck constant.
   - $c = 3 \times 10^8$ m/s is the speed of light.

    These constants show up all over in physics.  In the cell below write some code that assigns the constants to variables and then use the variables to calculate Rydberg's constant. Use a print statement to display the result.  The result should be: $R_\infty = 10961656.2162$ (in m$^{-1}$)



```{python}
# Python Code Here!
```

6. In Einstein's special theory of relativity, the momentum of an object with mass $m$ (in kg) and velocity $v$ (in m/s) is given by:$$ p = m v \gamma$$ where $$\gamma = {1\over \sqrt{1 - {v^2\over c^2}}}$$ with $c = 3 \times 10^8$ m/s

    1. Calculate the momentum of an object with mass $m = 0.14$ kg and speed $v = 50$ m/s.  Then compare to the classical expression for momentum: $p = mv$. 
    2. Now calculate the momentum of an object with mass $m = 0.14$ kg and whose speed is ${1 \over 4}$ the speed of light.  Repeat the comparison to the classical value.  
    3. Repeat for the following speeds: ${1\over 2}$ the speed of light, ${3\over 4}$ the speed of light, and ${7\over 8}$ the speed of light.  Repeat the comparison to the classical value.

```{python}
# Python Code Here!
```
